drop table askquestion;
drop table askquestionReply;
drop table basicEvaluation;
drop table itcertificate;
drop table itevaluation;
drop table jpcertificate;
drop table jpevaluation;
drop table memberstaff;
drop table memberstudent;
drop table memberstudentcertificate;
drop table memberstudentscore;
drop table memberstudentsurvey;
drop table news;
drop table memberbasic;
drop table registration;
drop table registerresult;
drop table survey;
drop table surveypage;
drop table surveyquestion;
drop table surveyoption;

drop sequence AskQuestionReplyNum_seq;
drop sequence askquestionNum_seq;
drop sequence basicEvaluationNum_seq;
drop sequence itevaluationnum_seq;
drop sequence jpevaluationnum_seq;
drop sequence membernum_seq;
drop sequence memberstudentscorenum_seq;
drop sequence memberstudentnum_seq;
drop sequence newsnum_seq;
drop sequence registrationnum_seq;
drop sequence teacherNum_seq;
drop sequence surveynum_seq;
drop sequence surveypagenum_seq;
drop sequence surveyquestionnum_seq;
drop sequence surveyoptionnum_seq;

create sequence AskQuestionReplyNum_seq;
create sequence askquestionNum_seq;
create sequence basicEvaluationNum_seq;
create sequence itevaluationnum_seq;
create sequence jpevaluationnum_seq;
create sequence membernum_seq;
create sequence memberstudentscorenum_seq;
create sequence memberstudentnum_seq;
create sequence newsnum_seq;
create sequence registrationnum_seq;
create sequence teacherNum_seq;
create sequence surveynum_seq;
create sequence surveypagenum_seq;
create sequence surveyquestionnum_seq;
create sequence surveyoptionnum_seq;

commit;

--------------------------------------------------------
--  File created - Saturday-April-07-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ASKQUESTION
--------------------------------------------------------

  CREATE TABLE "HR"."ASKQUESTION" 
   (	"ASKQUESTIONNUM" NUMBER, 
	"ID" VARCHAR2(20 BYTE), 
	"ASKQUESTIONTITLE" VARCHAR2(100 BYTE), 
	"ASKQUESTIONCONTENT" VARCHAR2(1000 BYTE), 
	"ASKQUESTIONDATE" DATE DEFAULT sysdate, 
	"ASKQUESTIONREPLIES" NUMBER(2,0) DEFAULT 0, 
	"DELETESTATUS" NUMBER(1,0) DEFAULT 0, 
	"DELETEBY" VARCHAR2(20 BYTE), 
	"DELETEDATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ASKQUESTIONREPLY
--------------------------------------------------------

  CREATE TABLE "HR"."ASKQUESTIONREPLY" 
   (	"ASKQUESTIONREPLYNUM" NUMBER, 
	"ASKQUESTIONNUM" NUMBER, 
	"ID" VARCHAR2(20 BYTE), 
	"TEXT" VARCHAR2(1000 BYTE), 
	"INPUTDATE" DATE DEFAULT sysdate					--작성날짜

   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BASICEVALUATION
--------------------------------------------------------

  CREATE TABLE "HR"."BASICEVALUATION" 
   (	"BASICEVALUATIONNUM" NUMBER, 
	"ID" VARCHAR2(20 BYTE), 
	"BASICATTENDANCE" NUMBER(3,0), 
	"BASICACTION" NUMBER(3,0), 
	"BASICBEHAVIOUR" NUMBER(3,0), 
	"BASICRULE" NUMBER(3,0), 
	"BASICEXPLANATORY" NUMBER(3,0), 
	"BASICCONSULT" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ITCERTIFICATE
--------------------------------------------------------

  CREATE TABLE "HR"."ITCERTIFICATE" 
   (	"ITCERTIFICATENUM" NUMBER(1,0), 
	"ITCERTIFICATENAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ITEVALUATION
--------------------------------------------------------

  CREATE TABLE "HR"."ITEVALUATION" 
   (	"ITEVALUATIONNUM" NUMBER, 
	"ID" VARCHAR2(20 BYTE), 
	"ITTESTFIRST" NUMBER(3,0), 
	"ITTESTSECOND" NUMBER(3,0), 
	"ITTESTTHIRD" NUMBER(3,0), 
	"ITPROJECTFIRST" NUMBER(3,0), 
	"ITPROJECTSECOND" NUMBER(3,0), 
	"ITPROJECTTHIRD" NUMBER(3,0), 
	"ITPROJECTFINAL" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table JPCERTIFICATE
--------------------------------------------------------

  CREATE TABLE "HR"."JPCERTIFICATE" 
   (	"JPCERTIFICATENUM" NUMBER(1,0), 
	"JPCERTIFICATENAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table JPEVALUATION
--------------------------------------------------------

  CREATE TABLE "HR"."JPEVALUATION" 
   (	"JPEVALUATIONNUM" NUMBER, 
	"ID" VARCHAR2(20 BYTE), 
	"JPTESTFIRST" NUMBER(3,0), 
	"JPTESTSECOND" NUMBER(3,0), 
	"JPTESTTHIRD" NUMBER(3,0), 
	"JPORALTESTFIRST" NUMBER(3,0), 
	"JPORALTESTSECOND" NUMBER(3,0), 
	"JPORALTESTTHIRD" NUMBER(3,0), 
	"JPTESTINTRODUCTION" NUMBER(3,0), 
	"JPTESTPRESENTATION" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBERBASIC
--------------------------------------------------------

  CREATE TABLE "HR"."MEMBERBASIC" 
   (	"MEMBERNUM" NUMBER, 
	"ID" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"MEMBERCLASS" VARCHAR2(10 BYTE), 
	"MEMBERPICNAME" VARCHAR2(1000 BYTE), 
	"MEMBERSAVERPICNAME" VARCHAR2(1000 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"PHONE" VARCHAR2(11 BYTE), 
	"ADDRESS" VARCHAR2(200 BYTE), 
	"POSTNUM" VARCHAR2(10 BYTE), 
	"DELETESTATUS" NUMBER(1,0) DEFAULT 0, 
	"DELETEBY" VARCHAR2(20 BYTE), 
	"DELETEDATE" DATE DEFAULT sysdate     -- 논리적 삭제 실행일
  , 
	"EMAILAPPROVAL" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBERSTAFF
--------------------------------------------------------

  CREATE TABLE "HR"."MEMBERSTAFF" 
   (	"TEACHERNUM" NUMBER, 
	"ID" VARCHAR2(20 BYTE), 
	"INCHARGEALUMNI" VARCHAR2(10 BYTE), 
	"INCHARGESUBJECT" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBERSTUDENT
--------------------------------------------------------

  CREATE TABLE "HR"."MEMBERSTUDENT" 
   (	"MEMBERSTUDENTNUM" NUMBER, 
	"ID" VARCHAR2(20 BYTE), 
	"ALUMNI" NUMBER(3,0), 
	"ITMAJOR" NUMBER(1,0) DEFAULT 0, 
	"JPMAJOR" NUMBER(1,0) DEFAULT 0, 
	"CLASSROOM" VARCHAR2(1 BYTE), 
	"GROUPNUM" NUMBER(2,0), 
	"SEAT" NUMBER(2,0), 
	"LATE" NUMBER(3,0) DEFAULT 0, 
	"EARLY" NUMBER(3,0) DEFAULT 0, 
	"ABSENT" NUMBER(3,0) DEFAULT 0	         -- 결석

  
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBERSTUDENTCERTIFICATE
--------------------------------------------------------

  CREATE TABLE "HR"."MEMBERSTUDENTCERTIFICATE" 
   (	"ID" VARCHAR2(20 BYTE), 
	"ITCERTIFICATE" NUMBER(1,0) DEFAULT 0, 
	"JPCERTIFICATE" NUMBER(1,0) DEFAULT 0, 
	"OTHERCERTIFICATE" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBERSTUDENTSCORE
--------------------------------------------------------

  CREATE TABLE "HR"."MEMBERSTUDENTSCORE" 
   (	"MEMBERSTUDENTSCORENUM" NUMBER, 
	"ID" VARCHAR2(20 BYTE), 
	"ITEVALUATION" NUMBER, 
	"JPEVALUATION" NUMBER, 
	"BASICEVALUATION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NEWS
--------------------------------------------------------

  CREATE TABLE "HR"."NEWS" 
   (	"NEWSNUM" NUMBER, 
	"ID" VARCHAR2(20 BYTE), 
	"TARGETALUMNI" NUMBER(3,0), 
	"TARGETCLASS" VARCHAR2(1 BYTE), 
	"NEWSTITLE" VARCHAR2(100 BYTE), 
	"NEWSHEADER" VARCHAR2(20 BYTE), 
	"NEWSCONTENT" VARCHAR2(1000 BYTE), 
	"NEWSFILENAME" VARCHAR2(1000 BYTE), 
	"NEWSSAVEDFILENAME" VARCHAR2(1000 BYTE), 
	"NEWSDATE" DATE DEFAULT sysdate, 
	"NEWSDISPLAY" NUMBER(1,0) DEFAULT 1, 
	"NEWSHITS" NUMBER DEFAULT 0, 
	"DELETESTATUS" NUMBER(1,0) DEFAULT 0, 
	"DELETEBY" VARCHAR2(20 BYTE), 
	"DELETEDATE" DATE DEFAULT sysdate				        -- 논리적 삭제 실행일

   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REGISTERRESULT
--------------------------------------------------------

  CREATE TABLE "HR"."REGISTERRESULT" 
   (	"REGISTERRESULT" NUMBER(1,0), 
	"REGISTERRESULTNAME" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REGISTRATION
--------------------------------------------------------

  CREATE TABLE "HR"."REGISTRATION" 
   (	"REGISTRATIONNUM" NUMBER, 
	"ID" VARCHAR2(20 BYTE), 
	"REGISTRATIONCONTENT" VARCHAR2(300 BYTE), 
	"ESTIMATEDTIME" VARCHAR2(30 BYTE), 
	"REGISTRATIONDATE" DATE DEFAULT sysdate, 
	"REGISTERRESULT" NUMBER(1,0) DEFAULT 0, 
	"DELETESTATUS" NUMBER(1,0) DEFAULT 0, 
	"DELETEBY" VARCHAR2(20 BYTE), 
	"DELETEDATE" DATE DEFAULT sysdate             -- 논리적 삭제 실행일

   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SURVEYOPTION
--------------------------------------------------------

  CREATE TABLE "HR"."SURVEYOPTION" 
   (	"SURVEYOPTIONNUM" NUMBER, 
	"SURVEYQUESTIONNUM" NUMBER, 
	"SURVEYOPTIONCONTENT" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SURVEY
--------------------------------------------------------

  CREATE TABLE "HR"."SURVEY" 
   (	"SURVEYNUM" NUMBER, 
	"TEACHERNUM" NUMBER, 
	"SURVEYTITLE" VARCHAR2(100 BYTE), 
	"SURVEYWRITTENDATE" DATE, 
	"SURVEYSTARTDATE" DATE, 
	"SURVEYENDDATE" DATE, 
	"SURVEYTARGETALUMNI" NUMBER, 
	"SURVEYTARGETCLASSROOM" VARCHAR2(20 BYTE) DEFAULT 'ALL', 
	"SURVEYPAGE" NUMBER DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SURVEYPAGE
--------------------------------------------------------

  CREATE TABLE "HR"."SURVEYPAGE" 
   (	"SURVEYPAGENUM" NUMBER, 
	"SURVEYNUM" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SURVEYQUESTION
--------------------------------------------------------

  CREATE TABLE "HR"."SURVEYQUESTION" 
   (	"SURVEYQUESTIONNUM" NUMBER, 
	"SURVEYPAGENUM" NUMBER, 
	"SURVEYQUESTIONCONTENT" VARCHAR2(300 BYTE), 
	"SURVEYQUESTIONTYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into HR.SURVEYQUESTION
SET DEFINE OFF;

Insert into HR.ASKQUESTION (ASKQUESTIONNUM,ID,ASKQUESTIONTITLE,ASKQUESTIONCONTENT,ASKQUESTIONDATE,ASKQUESTIONREPLIES,DELETESTATUS,DELETEBY,DELETEDATE) values (1,'testid2','쌤...배가 아파요','끄아아아악',to_date('18/04/07','RR/MM/DD'),0,0,' ',to_date('18/04/07','RR/MM/DD'));
REM INSERTING into HR.ASKQUESTIONREPLY
SET DEFINE OFF;
Insert into HR.ASKQUESTIONREPLY (ASKQUESTIONREPLYNUM,ASKQUESTIONNUM,ID,TEXT,INPUTDATE) values (1,1,'testid2','일본 가즈아아아아!',to_date('18/04/07','RR/MM/DD'));
REM INSERTING into HR.BASICEVALUATION
SET DEFINE OFF;
Insert into HR.BASICEVALUATION (BASICEVALUATIONNUM,ID,BASICATTENDANCE,BASICACTION,BASICBEHAVIOUR,BASICRULE,BASICEXPLANATORY,BASICCONSULT) values (1,'testid2',80,70,50,60,2,4);
REM INSERTING into HR.ITCERTIFICATE
SET DEFINE OFF;
Insert into HR.ITCERTIFICATE (ITCERTIFICATENUM,ITCERTIFICATENAME) values (0,'없음');
Insert into HR.ITCERTIFICATE (ITCERTIFICATENUM,ITCERTIFICATENAME) values (1,'정보처리산업기사');
Insert into HR.ITCERTIFICATE (ITCERTIFICATENUM,ITCERTIFICATENAME) values (2,'정보처리기사');
Insert into HR.ITCERTIFICATE (ITCERTIFICATENUM,ITCERTIFICATENAME) values (3,'정보처리기사, 정보처리산업기사');
REM INSERTING into HR.ITEVALUATION
SET DEFINE OFF;
Insert into HR.ITEVALUATION (ITEVALUATIONNUM,ID,ITTESTFIRST,ITTESTSECOND,ITTESTTHIRD,ITPROJECTFIRST,ITPROJECTSECOND,ITPROJECTTHIRD,ITPROJECTFINAL) values (1,'testid2',33,36,80,70,90,100,40);
REM INSERTING into HR.JPCERTIFICATE
SET DEFINE OFF;
Insert into HR.JPCERTIFICATE (JPCERTIFICATENUM,JPCERTIFICATENAME) values (0,'없음');
Insert into HR.JPCERTIFICATE (JPCERTIFICATENUM,JPCERTIFICATENAME) values (1,'JLPT 1급');
Insert into HR.JPCERTIFICATE (JPCERTIFICATENUM,JPCERTIFICATENAME) values (2,'JLPT 2급');
Insert into HR.JPCERTIFICATE (JPCERTIFICATENUM,JPCERTIFICATENAME) values (3,'JLPT 3급');
REM INSERTING into HR.JPEVALUATION
SET DEFINE OFF;
Insert into HR.JPEVALUATION (JPEVALUATIONNUM,ID,JPTESTFIRST,JPTESTSECOND,JPTESTTHIRD,JPORALTESTFIRST,JPORALTESTSECOND,JPORALTESTTHIRD,JPTESTINTRODUCTION,JPTESTPRESENTATION) values (1,'testid2',54,66,42,14,68,88,41,70);
REM INSERTING into HR.MEMBERBASIC
SET DEFINE OFF;
Insert into HR.MEMBERBASIC (MEMBERNUM,ID,PASSWORD,MEMBERCLASS,MEMBERPICNAME,MEMBERSAVERPICNAME,NAME,EMAIL,PHONE,ADDRESS,POSTNUM,DELETESTATUS,DELETEBY,DELETEDATE,EMAILAPPROVAL) values (1,'testid','password','teacher',null,null,'이름','aaa@aa.com','0104445555','서울시 강남구 삼성동 코엑스 4층','15425',0,' ',to_date('18/04/02','RR/MM/DD'),1);
Insert into HR.MEMBERBASIC (MEMBERNUM,ID,PASSWORD,MEMBERCLASS,MEMBERPICNAME,MEMBERSAVERPICNAME,NAME,EMAIL,PHONE,ADDRESS,POSTNUM,DELETESTATUS,DELETEBY,DELETEDATE,EMAILAPPROVAL) values (2,'testid2','password','student',null,null,'이름2','aaa2@aa.com','0104445555','서울시 강남구 삼성동 코엑스 4층','15425',0,' ',to_date('18/04/02','RR/MM/DD'),1);
Insert into HR.MEMBERBASIC (MEMBERNUM,ID,PASSWORD,MEMBERCLASS,MEMBERPICNAME,MEMBERSAVERPICNAME,NAME,EMAIL,PHONE,ADDRESS,POSTNUM,DELETESTATUS,DELETEBY,DELETEDATE,EMAILAPPROVAL) values (3,'testid4','password','teacher',null,null,'이름3','aaa@aa.com','0104445555','서울시 강남구 삼성동 코엑스 4층','15425',0,' ',to_date('18/04/02','RR/MM/DD'),1);
Insert into HR.MEMBERBASIC (MEMBERNUM,ID,PASSWORD,MEMBERCLASS,MEMBERPICNAME,MEMBERSAVERPICNAME,NAME,EMAIL,PHONE,ADDRESS,POSTNUM,DELETESTATUS,DELETEBY,DELETEDATE,EMAILAPPROVAL) values (5,'testid5','password','teacher',null,null,'이름4','aaa@aa.com','0104445555','서울시 강남구 삼성동 코엑스 4층','15425',0,' ',to_date('18/04/02','RR/MM/DD'),1);
Insert into HR.MEMBERBASIC (MEMBERNUM,ID,PASSWORD,MEMBERCLASS,MEMBERPICNAME,MEMBERSAVERPICNAME,NAME,EMAIL,PHONE,ADDRESS,POSTNUM,DELETESTATUS,DELETEBY,DELETEDATE,EMAILAPPROVAL) values (6,'testid6','password','teacher',null,null,'이름5','aaa@aa.com','0104445555','서울시 강남구 삼성동 코엑스 4층','15425',0,' ',to_date('18/04/02','RR/MM/DD'),1);
Insert into HR.MEMBERBASIC (MEMBERNUM,ID,PASSWORD,MEMBERCLASS,MEMBERPICNAME,MEMBERSAVERPICNAME,NAME,EMAIL,PHONE,ADDRESS,POSTNUM,DELETESTATUS,DELETEBY,DELETEDATE,EMAILAPPROVAL) values (7,'testid7','password','teacher',null,null,'이름6','aaa@aa.com','0104445555','서울시 강남구 삼성동 코엑스 4층','15425',0,' ',to_date('18/04/02','RR/MM/DD'),1);
Insert into HR.MEMBERBASIC (MEMBERNUM,ID,PASSWORD,MEMBERCLASS,MEMBERPICNAME,MEMBERSAVERPICNAME,NAME,EMAIL,PHONE,ADDRESS,POSTNUM,DELETESTATUS,DELETEBY,DELETEDATE,EMAILAPPROVAL) values (8,'testid8','password','student',null,null,'이름7','aaa2@aa.com','0104445555','서울시 강남구 삼성동 코엑스 4층','15425',0,' ',to_date('18/04/02','RR/MM/DD'),1);
Insert into HR.MEMBERBASIC (MEMBERNUM,ID,PASSWORD,MEMBERCLASS,MEMBERPICNAME,MEMBERSAVERPICNAME,NAME,EMAIL,PHONE,ADDRESS,POSTNUM,DELETESTATUS,DELETEBY,DELETEDATE,EMAILAPPROVAL) values (9,'testid9','password','student',null,null,'이름8','aaa2@aa.com','0104445555','서울시 강남구 삼성동 코엑스 4층','15425',0,' ',to_date('18/04/02','RR/MM/DD'),1);
Insert into HR.MEMBERBASIC (MEMBERNUM,ID,PASSWORD,MEMBERCLASS,MEMBERPICNAME,MEMBERSAVERPICNAME,NAME,EMAIL,PHONE,ADDRESS,POSTNUM,DELETESTATUS,DELETEBY,DELETEDATE,EMAILAPPROVAL) values (10,'testid10','password','student',null,null,'이름9','aaa2@aa.com','0104445555','서울시 강남구 삼성동 코엑스 4층','15425',0,' ',to_date('18/04/02','RR/MM/DD'),1);
Insert into HR.MEMBERBASIC (MEMBERNUM,ID,PASSWORD,MEMBERCLASS,MEMBERPICNAME,MEMBERSAVERPICNAME,NAME,EMAIL,PHONE,ADDRESS,POSTNUM,DELETESTATUS,DELETEBY,DELETEDATE,EMAILAPPROVAL) values (11,'testid11','password','student',null,null,'이름10','aaa2@aa.com','0104445555','서울시 강남구 삼성동 코엑스 4층','15425',0,' ',to_date('18/04/02','RR/MM/DD'),1);
Insert into HR.MEMBERBASIC (MEMBERNUM,ID,PASSWORD,MEMBERCLASS,MEMBERPICNAME,MEMBERSAVERPICNAME,NAME,EMAIL,PHONE,ADDRESS,POSTNUM,DELETESTATUS,DELETEBY,DELETEDATE,EMAILAPPROVAL) values (12,'testid12','password','student',null,null,'이름11','aaa2@aa.com','0104445555','서울시 강남구 삼성동 코엑스 4층','15425',0,' ',to_date('18/04/02','RR/MM/DD'),1);
Insert into HR.MEMBERBASIC (MEMBERNUM,ID,PASSWORD,MEMBERCLASS,MEMBERPICNAME,MEMBERSAVERPICNAME,NAME,EMAIL,PHONE,ADDRESS,POSTNUM,DELETESTATUS,DELETEBY,DELETEDATE,EMAILAPPROVAL) values (13,'testid13','password','student',null,null,'이름12','aaa2@aa.com','0104445555','서울시 강남구 삼성동 코엑스 4층','15425',0,' ',to_date('18/04/02','RR/MM/DD'),1);
REM INSERTING into HR.MEMBERSTAFF
SET DEFINE OFF;
Insert into HR.MEMBERSTAFF (TEACHERNUM,ID,INCHARGEALUMNI,INCHARGESUBJECT) values (1,'testid','1','IT');
Insert into HR.MEMBERSTAFF (TEACHERNUM,ID,INCHARGEALUMNI,INCHARGESUBJECT) values (2,'testid4','1','JP');
Insert into HR.MEMBERSTAFF (TEACHERNUM,ID,INCHARGEALUMNI,INCHARGESUBJECT) values (3,'testid5','1','SM');
Insert into HR.MEMBERSTAFF (TEACHERNUM,ID,INCHARGEALUMNI,INCHARGESUBJECT) values (4,'testid6','2','IT');
Insert into HR.MEMBERSTAFF (TEACHERNUM,ID,INCHARGEALUMNI,INCHARGESUBJECT) values (5,'testid7','2','JP');
REM INSERTING into HR.MEMBERSTUDENT
SET DEFINE OFF;
Insert into HR.MEMBERSTUDENT (MEMBERSTUDENTNUM,ID,ALUMNI,ITMAJOR,JPMAJOR,CLASSROOM,GROUPNUM,SEAT,LATE,EARLY,ABSENT) values (1,'testid2',1,0,0,'A',9,25,1,1,3);
Insert into HR.MEMBERSTUDENT (MEMBERSTUDENTNUM,ID,ALUMNI,ITMAJOR,JPMAJOR,CLASSROOM,GROUPNUM,SEAT,LATE,EARLY,ABSENT) values (2,'testid8',1,0,0,'B',9,25,1,1,3);
Insert into HR.MEMBERSTUDENT (MEMBERSTUDENTNUM,ID,ALUMNI,ITMAJOR,JPMAJOR,CLASSROOM,GROUPNUM,SEAT,LATE,EARLY,ABSENT) values (3,'testid9',1,0,0,'C',9,25,1,1,3);
Insert into HR.MEMBERSTUDENT (MEMBERSTUDENTNUM,ID,ALUMNI,ITMAJOR,JPMAJOR,CLASSROOM,GROUPNUM,SEAT,LATE,EARLY,ABSENT) values (4,'testid10',1,0,0,'D',9,25,1,1,3);
Insert into HR.MEMBERSTUDENT (MEMBERSTUDENTNUM,ID,ALUMNI,ITMAJOR,JPMAJOR,CLASSROOM,GROUPNUM,SEAT,LATE,EARLY,ABSENT) values (5,'testid11',1,0,0,'E',9,25,1,1,3);
Insert into HR.MEMBERSTUDENT (MEMBERSTUDENTNUM,ID,ALUMNI,ITMAJOR,JPMAJOR,CLASSROOM,GROUPNUM,SEAT,LATE,EARLY,ABSENT) values (6,'testid12',2,0,0,'B',9,25,1,1,3);
Insert into HR.MEMBERSTUDENT (MEMBERSTUDENTNUM,ID,ALUMNI,ITMAJOR,JPMAJOR,CLASSROOM,GROUPNUM,SEAT,LATE,EARLY,ABSENT) values (7,'testid13',2,0,0,'C',9,25,1,1,3);
REM INSERTING into HR.MEMBERSTUDENTCERTIFICATE
SET DEFINE OFF;
Insert into HR.MEMBERSTUDENTCERTIFICATE (ID,ITCERTIFICATE,JPCERTIFICATE,OTHERCERTIFICATE) values ('testid2',1,0,' ');
REM INSERTING into HR.MEMBERSTUDENTSCORE
SET DEFINE OFF;
Insert into HR.MEMBERSTUDENTSCORE (MEMBERSTUDENTSCORENUM,ID,ITEVALUATION,JPEVALUATION,BASICEVALUATION) values (1,'testid2',2,2,2);
REM INSERTING into HR.NEWS
SET DEFINE OFF;
Insert into HR.NEWS (NEWSNUM,ID,TARGETALUMNI,TARGETCLASS,NEWSTITLE,NEWSHEADER,NEWSCONTENT,NEWSFILENAME,NEWSSAVEDFILENAME,NEWSDATE,NEWSDISPLAY,NEWSHITS,DELETESTATUS,DELETEBY,DELETEDATE) values (1,'testid',34,'A','TEST NEWS 빨리 나가고 싶다','중요','여러분은 여기서 이제 나갈 수 없습니다.',' ',' ',to_date('18/04/07','RR/MM/DD'),1,0,0,' ',to_date('18/04/07','RR/MM/DD'));
REM INSERTING into HR.REGISTERRESULT
SET DEFINE OFF;
Insert into HR.REGISTERRESULT (REGISTERRESULT,REGISTERRESULTNAME) values (0,'출석');
Insert into HR.REGISTERRESULT (REGISTERRESULT,REGISTERRESULTNAME) values (1,'지각');
Insert into HR.REGISTERRESULT (REGISTERRESULT,REGISTERRESULTNAME) values (2,'결석');
REM INSERTING into HR.REGISTRATION
SET DEFINE OFF;
Insert into HR.REGISTRATION (REGISTRATIONNUM,ID,REGISTRATIONCONTENT,ESTIMATEDTIME,REGISTRATIONDATE,REGISTERRESULT,DELETESTATUS,DELETEBY,DELETEDATE) values (1,'testid2','쌤 저 늦잠자서 늦어요 ㅈㅅ','오후 9시 00분',to_date('18/04/07','RR/MM/DD'),0,0,' ',to_date('18/04/07','RR/MM/DD'));
REM INSERTING into HR.SURVEYOPTION
SET DEFINE OFF;
REM INSERTING into HR.SURVEY
SET DEFINE OFF;
Insert into HR.SURVEY (SURVEYNUM,TEACHERNUM,SURVEYTITLE,SURVEYWRITTENDATE,SURVEYSTARTDATE,SURVEYENDDATE,SURVEYTARGETALUMNI,SURVEYTARGETCLASSROOM,SURVEYPAGE) values (1,1,'it 성취도에 관한 설문',to_date('18/04/05','RR/MM/DD'),to_date('18/04/05','RR/MM/DD'),to_date('18/04/05','RR/MM/DD'),1,'ALL',1);
REM INSERTING into HR.SURVEYPAGE
SET DEFINE OFF;
REM INSERTING into HR.SURVEYQUESTION
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C0012421
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C0012421" ON "HR"."ASKQUESTION" ("ASKQUESTIONNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0012465
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C0012465" ON "HR"."ASKQUESTIONREPLY" ("ASKQUESTIONREPLYNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0012460
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C0012460" ON "HR"."BASICEVALUATION" ("BASICEVALUATIONNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0012412
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C0012412" ON "HR"."ITCERTIFICATE" ("ITCERTIFICATENUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0012440
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C0012440" ON "HR"."ITEVALUATION" ("ITEVALUATIONNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0012413
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C0012413" ON "HR"."JPCERTIFICATE" ("JPCERTIFICATENUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0012451
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C0012451" ON "HR"."JPEVALUATION" ("JPEVALUATIONNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0015323
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C0015323" ON "HR"."MEMBERBASIC" ("MEMBERNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0015324
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C0015324" ON "HR"."MEMBERBASIC" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0015328
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C0015328" ON "HR"."MEMBERSTAFF" ("TEACHERNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0015334
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C0015334" ON "HR"."MEMBERSTUDENT" ("MEMBERSTUDENTNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0012427
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C0012427" ON "HR"."MEMBERSTUDENTSCORE" ("MEMBERSTUDENTSCORENUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0012396
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C0012396" ON "HR"."NEWS" ("NEWSNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0012406
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C0012406" ON "HR"."REGISTERRESULT" ("REGISTERRESULT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0012481
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C0012481" ON "HR"."SURVEYOPTION" ("SURVEYOPTIONNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0015516
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C0015516" ON "HR"."SURVEY" ("SURVEYNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0012477
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C0012477" ON "HR"."SURVEYPAGE" ("SURVEYPAGENUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0012479
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C0012479" ON "HR"."SURVEYQUESTION" ("SURVEYQUESTIONNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ASKQUESTION
--------------------------------------------------------

  ALTER TABLE "HR"."ASKQUESTION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."ASKQUESTION" MODIFY ("ASKQUESTIONTITLE" NOT NULL ENABLE);
  ALTER TABLE "HR"."ASKQUESTION" MODIFY ("ASKQUESTIONCONTENT" NOT NULL ENABLE);
  ALTER TABLE "HR"."ASKQUESTION" MODIFY ("ASKQUESTIONDATE" NOT NULL ENABLE);
  ALTER TABLE "HR"."ASKQUESTION" MODIFY ("DELETESTATUS" NOT NULL ENABLE);
  ALTER TABLE "HR"."ASKQUESTION" MODIFY ("DELETEBY" NOT NULL ENABLE);
  ALTER TABLE "HR"."ASKQUESTION" MODIFY ("DELETEDATE" NOT NULL ENABLE);
  ALTER TABLE "HR"."ASKQUESTION" ADD PRIMARY KEY ("ASKQUESTIONNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ASKQUESTIONREPLY
--------------------------------------------------------

  ALTER TABLE "HR"."ASKQUESTIONREPLY" MODIFY ("ASKQUESTIONNUM" NOT NULL ENABLE);
  ALTER TABLE "HR"."ASKQUESTIONREPLY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."ASKQUESTIONREPLY" MODIFY ("TEXT" NOT NULL ENABLE);
  ALTER TABLE "HR"."ASKQUESTIONREPLY" ADD PRIMARY KEY ("ASKQUESTIONREPLYNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BASICEVALUATION
--------------------------------------------------------

  ALTER TABLE "HR"."BASICEVALUATION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."BASICEVALUATION" MODIFY ("BASICATTENDANCE" NOT NULL ENABLE);
  ALTER TABLE "HR"."BASICEVALUATION" MODIFY ("BASICACTION" NOT NULL ENABLE);
  ALTER TABLE "HR"."BASICEVALUATION" MODIFY ("BASICBEHAVIOUR" NOT NULL ENABLE);
  ALTER TABLE "HR"."BASICEVALUATION" MODIFY ("BASICRULE" NOT NULL ENABLE);
  ALTER TABLE "HR"."BASICEVALUATION" MODIFY ("BASICEXPLANATORY" NOT NULL ENABLE);
  ALTER TABLE "HR"."BASICEVALUATION" MODIFY ("BASICCONSULT" NOT NULL ENABLE);
  ALTER TABLE "HR"."BASICEVALUATION" ADD PRIMARY KEY ("BASICEVALUATIONNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ITCERTIFICATE
--------------------------------------------------------

  ALTER TABLE "HR"."ITCERTIFICATE" ADD PRIMARY KEY ("ITCERTIFICATENUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ITEVALUATION
--------------------------------------------------------

  ALTER TABLE "HR"."ITEVALUATION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."ITEVALUATION" MODIFY ("ITTESTFIRST" NOT NULL ENABLE);
  ALTER TABLE "HR"."ITEVALUATION" MODIFY ("ITTESTSECOND" NOT NULL ENABLE);
  ALTER TABLE "HR"."ITEVALUATION" MODIFY ("ITTESTTHIRD" NOT NULL ENABLE);
  ALTER TABLE "HR"."ITEVALUATION" MODIFY ("ITPROJECTFIRST" NOT NULL ENABLE);
  ALTER TABLE "HR"."ITEVALUATION" MODIFY ("ITPROJECTSECOND" NOT NULL ENABLE);
  ALTER TABLE "HR"."ITEVALUATION" MODIFY ("ITPROJECTTHIRD" NOT NULL ENABLE);
  ALTER TABLE "HR"."ITEVALUATION" MODIFY ("ITPROJECTFINAL" NOT NULL ENABLE);
  ALTER TABLE "HR"."ITEVALUATION" ADD PRIMARY KEY ("ITEVALUATIONNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table JPCERTIFICATE
--------------------------------------------------------

  ALTER TABLE "HR"."JPCERTIFICATE" ADD PRIMARY KEY ("JPCERTIFICATENUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table JPEVALUATION
--------------------------------------------------------

  ALTER TABLE "HR"."JPEVALUATION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."JPEVALUATION" MODIFY ("JPTESTFIRST" NOT NULL ENABLE);
  ALTER TABLE "HR"."JPEVALUATION" MODIFY ("JPTESTSECOND" NOT NULL ENABLE);
  ALTER TABLE "HR"."JPEVALUATION" MODIFY ("JPTESTTHIRD" NOT NULL ENABLE);
  ALTER TABLE "HR"."JPEVALUATION" MODIFY ("JPORALTESTFIRST" NOT NULL ENABLE);
  ALTER TABLE "HR"."JPEVALUATION" MODIFY ("JPORALTESTSECOND" NOT NULL ENABLE);
  ALTER TABLE "HR"."JPEVALUATION" MODIFY ("JPORALTESTTHIRD" NOT NULL ENABLE);
  ALTER TABLE "HR"."JPEVALUATION" MODIFY ("JPTESTINTRODUCTION" NOT NULL ENABLE);
  ALTER TABLE "HR"."JPEVALUATION" MODIFY ("JPTESTPRESENTATION" NOT NULL ENABLE);
  ALTER TABLE "HR"."JPEVALUATION" ADD PRIMARY KEY ("JPEVALUATIONNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBERBASIC
--------------------------------------------------------

  ALTER TABLE "HR"."MEMBERBASIC" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."MEMBERBASIC" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "HR"."MEMBERBASIC" MODIFY ("MEMBERCLASS" NOT NULL ENABLE);
  ALTER TABLE "HR"."MEMBERBASIC" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "HR"."MEMBERBASIC" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "HR"."MEMBERBASIC" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "HR"."MEMBERBASIC" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "HR"."MEMBERBASIC" MODIFY ("POSTNUM" NOT NULL ENABLE);
  ALTER TABLE "HR"."MEMBERBASIC" MODIFY ("DELETESTATUS" NOT NULL ENABLE);
  ALTER TABLE "HR"."MEMBERBASIC" MODIFY ("DELETEBY" NOT NULL ENABLE);
  ALTER TABLE "HR"."MEMBERBASIC" ADD PRIMARY KEY ("MEMBERNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."MEMBERBASIC" ADD UNIQUE ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."MEMBERBASIC" MODIFY ("EMAILAPPROVAL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBERSTAFF
--------------------------------------------------------

  ALTER TABLE "HR"."MEMBERSTAFF" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."MEMBERSTAFF" MODIFY ("INCHARGEALUMNI" NOT NULL ENABLE);
  ALTER TABLE "HR"."MEMBERSTAFF" MODIFY ("INCHARGESUBJECT" NOT NULL ENABLE);
  ALTER TABLE "HR"."MEMBERSTAFF" ADD PRIMARY KEY ("TEACHERNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBERSTUDENT
--------------------------------------------------------

  ALTER TABLE "HR"."MEMBERSTUDENT" MODIFY ("ALUMNI" NOT NULL ENABLE);
  ALTER TABLE "HR"."MEMBERSTUDENT" MODIFY ("CLASSROOM" NOT NULL ENABLE);
  ALTER TABLE "HR"."MEMBERSTUDENT" MODIFY ("GROUPNUM" NOT NULL ENABLE);
  ALTER TABLE "HR"."MEMBERSTUDENT" MODIFY ("SEAT" NOT NULL ENABLE);
  ALTER TABLE "HR"."MEMBERSTUDENT" ADD PRIMARY KEY ("MEMBERSTUDENTNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBERSTUDENTCERTIFICATE
--------------------------------------------------------

  ALTER TABLE "HR"."MEMBERSTUDENTCERTIFICATE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."MEMBERSTUDENTCERTIFICATE" MODIFY ("ITCERTIFICATE" NOT NULL ENABLE);
  ALTER TABLE "HR"."MEMBERSTUDENTCERTIFICATE" MODIFY ("JPCERTIFICATE" NOT NULL ENABLE);
  ALTER TABLE "HR"."MEMBERSTUDENTCERTIFICATE" MODIFY ("OTHERCERTIFICATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBERSTUDENTSCORE
--------------------------------------------------------

  ALTER TABLE "HR"."MEMBERSTUDENTSCORE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."MEMBERSTUDENTSCORE" MODIFY ("ITEVALUATION" NOT NULL ENABLE);
  ALTER TABLE "HR"."MEMBERSTUDENTSCORE" MODIFY ("JPEVALUATION" NOT NULL ENABLE);
  ALTER TABLE "HR"."MEMBERSTUDENTSCORE" MODIFY ("BASICEVALUATION" NOT NULL ENABLE);
  ALTER TABLE "HR"."MEMBERSTUDENTSCORE" ADD PRIMARY KEY ("MEMBERSTUDENTSCORENUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table NEWS
--------------------------------------------------------

  ALTER TABLE "HR"."NEWS" MODIFY ("NEWSNUM" NOT NULL ENABLE);
  ALTER TABLE "HR"."NEWS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."NEWS" MODIFY ("TARGETALUMNI" NOT NULL ENABLE);
  ALTER TABLE "HR"."NEWS" MODIFY ("TARGETCLASS" NOT NULL ENABLE);
  ALTER TABLE "HR"."NEWS" MODIFY ("NEWSTITLE" NOT NULL ENABLE);
  ALTER TABLE "HR"."NEWS" MODIFY ("NEWSCONTENT" NOT NULL ENABLE);
  ALTER TABLE "HR"."NEWS" MODIFY ("DELETEBY" NOT NULL ENABLE);
  ALTER TABLE "HR"."NEWS" ADD PRIMARY KEY ("NEWSNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REGISTERRESULT
--------------------------------------------------------

  ALTER TABLE "HR"."REGISTERRESULT" MODIFY ("REGISTERRESULTNAME" NOT NULL ENABLE);
  ALTER TABLE "HR"."REGISTERRESULT" ADD PRIMARY KEY ("REGISTERRESULT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REGISTRATION
--------------------------------------------------------

  ALTER TABLE "HR"."REGISTRATION" MODIFY ("REGISTRATIONNUM" NOT NULL ENABLE);
  ALTER TABLE "HR"."REGISTRATION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."REGISTRATION" MODIFY ("REGISTRATIONCONTENT" NOT NULL ENABLE);
  ALTER TABLE "HR"."REGISTRATION" MODIFY ("ESTIMATEDTIME" NOT NULL ENABLE);
  ALTER TABLE "HR"."REGISTRATION" MODIFY ("DELETESTATUS" NOT NULL ENABLE);
  ALTER TABLE "HR"."REGISTRATION" MODIFY ("DELETEBY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SURVEYOPTION
--------------------------------------------------------

  ALTER TABLE "HR"."SURVEYOPTION" ADD PRIMARY KEY ("SURVEYOPTIONNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SURVEY
--------------------------------------------------------

  ALTER TABLE "HR"."SURVEY" MODIFY ("TEACHERNUM" NOT NULL ENABLE);
  ALTER TABLE "HR"."SURVEY" MODIFY ("SURVEYTITLE" NOT NULL ENABLE);
  ALTER TABLE "HR"."SURVEY" MODIFY ("SURVEYWRITTENDATE" NOT NULL ENABLE);
  ALTER TABLE "HR"."SURVEY" MODIFY ("SURVEYSTARTDATE" NOT NULL ENABLE);
  ALTER TABLE "HR"."SURVEY" MODIFY ("SURVEYENDDATE" NOT NULL ENABLE);
  ALTER TABLE "HR"."SURVEY" MODIFY ("SURVEYTARGETALUMNI" NOT NULL ENABLE);
  ALTER TABLE "HR"."SURVEY" MODIFY ("SURVEYTARGETCLASSROOM" NOT NULL ENABLE);
  ALTER TABLE "HR"."SURVEY" ADD PRIMARY KEY ("SURVEYNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SURVEYPAGE
--------------------------------------------------------

  ALTER TABLE "HR"."SURVEYPAGE" ADD PRIMARY KEY ("SURVEYPAGENUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SURVEYQUESTION
--------------------------------------------------------

  ALTER TABLE "HR"."SURVEYQUESTION" ADD PRIMARY KEY ("SURVEYQUESTIONNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
